name: Deploy Polly Audio (Beta & Prod)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  synthesize-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_polly-use-case-prod}}
      S3_BUCKET_NAME: ${{ secrets.S3_polly- }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Generate and Upload Polly Audio
        run: |
          python synthesize.py